In [25]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
import random

In [26]:
product_types =[
        'gummies',
        'chocolates',
        'hard candies',
        'gum',
        'caramel',
        'other'
    ]
data = pd.DataFrame()
for i in range(1,1001):
    product_id = i
    product_type = product_types[random.randint(0, 5)]
    popularity_scale = random.randint(1, 10)
    durability_scale = random.randint(1, 10)
    price_scale = random.randint(1, 10)
    tempData = pd.DataFrame(
        [[
            product_id,
            product_type,
            popularity_scale,
            durability_scale,
            price_scale
        ]],
        columns = [
            'product_id',
            'product_type',
            'popularity_scale',
            'calories_scale',
            'price_scale'
        ]
    )
    data = pd.concat([tempData, data])
data.head()

   product_id  product_type  popularity_scale  calories_scale  price_scale
0        1000         other                 5              10            2
0         999  hard candies                 7               7            1
0         998    chocolates                 9               9            1
0         997  hard candies                 6              10            2
0         996  hard candies                 3               3            9

In [27]:
nn_data = data.drop(['popularity_scale'], axis=1)
dummy_df = pd.get_dummies(nn_data['product_type'])
nn_data = pd.concat([nn_data, dummy_df], axis=1)
nn_data = nn_data.drop('product_type', axis=1)
model = NearestNeighbors(n_neighbors=5)
nn_data.head()

,product_id,calories_scale,price_scale,caramel,chocolates,gum,gummies,hard candies,other
0,1000,10,2,0,0,0,0,0,1
0,999,7,1,0,0,0,0,1,0
0,998,9,1,0,1,0,0,0,0
0,997,10,2,0,0,0,0,1,0
0,996,3,9,0,0,0,0,1,0

In [28]:
model.fit(nn_data)

NearestNeighbors()

In [29]:
# product to reccommend on randomized for example
row_to_predict = nn_data.iloc[random.randint(0, 1000)]
prediction_indices = model.kneighbors([row_to_predict])[1][0]
nearest_neighbors = nn_data.iloc[prediction_indices]
row_to_predict

C:\Users\wasadmin\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(

product_id        477
calories_scale      5
price_scale         8
caramel             0
chocolates          0
gum                 1
gummies             0
hard candies        0
other               0
Name: 0, dtype: int64

In [30]:
nearest_neighbors

,product_id,calories_scale,price_scale,caramel,chocolates,gum,gummies,hard candies,other
0,477,5,8,0,0,1,0,0,0
0,478,2,9,0,0,0,0,0,1
0,475,9,5,0,1,0,0,0,0
0,474,9,10,0,0,0,0,0,1
0,481,2,5,0,1,0,0,0,0