In [9]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
import random

In [10]:
product_types =[
        'Commercial Auto & Trucking',
        'Cyber',
        'General Liability',
        'Management & Professional Liability',
        'Property',
        'Business Owner Policy',
        'Surety Bonds',
        'Workers Compensation',
        'Car',
        'Home',
        'Renters',
        'Condo',
        'Landlord',
        'Boat & Yacht',
        'Flood',
        'Motorcycle',
        'Travel',
        'Pet',
        'Weddings & Events',
        'Umbrella',
        'Other'
    ]
data = pd.DataFrame()
for i in range(1,1001):
    product_id = i
    product_type = product_types[random.randint(0, 20)]
    popularity_scale = random.randint(1, 10)
    durability_scale = random.randint(1, 10)
    price_scale = random.randint(1, 10)
    tempData = pd.DataFrame(
        [[
            product_id,
            product_type,
            popularity_scale,
            durability_scale,
            price_scale
        ]],
        columns = [
            'product_id',
            'product_type',
            'popularity_scale',
            'durability_scale',
            'price_scale'
        ]
    )
    data = pd.concat([tempData, data])
data.head()

,product_id,product_type,popularity_scale,durability_scale,price_scale
0,1000,Business Owner Policy,3,1,6
0,999,Business Owner Policy,10,6,2
0,998,Landlord,4,8,10
0,997,Weddings & Events,6,2,8
0,996,Umbrella,1,3,2

In [12]:
nn_data = data.drop(['popularity_scale'], axis=1)
dummy_df = pd.get_dummies(nn_data['product_type'])
nn_data = pd.concat([nn_data, dummy_df], axis=1)
nn_data = nn_data.drop('product_type', axis=1)
model = NearestNeighbors(n_neighbors=5)
nn_data.head()

,product_id,durability_scale,price_scale,Boat & Yacht,Business Owner Policy,Car,Commercial Auto & Trucking,Condo,Cyber,Flood,...,Motorcycle,Other,Pet,Property,Renters,Surety Bonds,Travel,Umbrella,Weddings & Events,Workers Compensation
0,1000,1,6,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,999,6,2,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,998,8,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,997,2,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
0,996,3,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [13]:
model.fit(nn_data)

NearestNeighbors()

In [14]:
# product to reccommend on randomized for example
row_to_predict = nn_data.iloc[random.randint(0, 1000)]
prediction_indices = model.kneighbors([row_to_predict])[1][0]
nearest_neighbors = nn_data.iloc[prediction_indices]

C:\Users\wasadmin\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(

In [15]:
nearest_neighbors

,product_id,durability_scale,price_scale,Boat & Yacht,Business Owner Policy,Car,Commercial Auto & Trucking,Condo,Cyber,Flood,...,Motorcycle,Other,Pet,Property,Renters,Surety Bonds,Travel,Umbrella,Weddings & Events,Workers Compensation
0,849,3,2,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,847,3,3,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
0,851,2,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
0,852,3,2,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
0,854,2,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0